# Generated by Django 5.2.1 on 2025-06-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_broadcast_category_faqentry_order_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartitem',
            name='product',
            field=models.ForeignKey(help_text='Товар, добавленный в корзину.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='clients.product', verbose_name='Товар'),
        ),
    ]
