# Generated by Django 5.2.1 on 2025-06-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_usercartitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название канала или группы.', max_length=255, verbose_name='Название канала')),
                ('channel_id', models.BigIntegerField(help_text='Уникальный идентификатор канала в Telegram.', unique=True, verbose_name='Telegram ID канала')),
                ('is_active', models.BooleanField(default=False, help_text='Флаг, указывающий, какой канал или группу активировать для подписки.', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ['name'],
            },
        ),
    ]
