# Generated by Django 5.2.1 on 2025-06-04 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_category_name_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Категория, к которой принадлежит товар.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.category', verbose_name='Категория'),
        ),
    ]
