# Generated by Django 5.2.1 on 2025-06-04 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_category_name_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, оформивший заказ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.telegramuser', verbose_name='Пользователь'),
        ),
    ]
